@urlRoot = http://localhost:3000
@urlApi = http://localhost:3000/api
GET {{ urlRoot }}/

### Get All Users
GET {{ urlApi }}/users
Accept: application/json

### Create User
POST {{ urlApi }}/users
Content-Type: application/json

{
  "username": "Moolie",
  "password": "123456789"
}


### Update User
PUT {{ urlApi }}/users/3
Content-Type: application/json

{
	"username": "Moolie updated",
	"password": "123456789"
}


### Delete User
DELETE {{urlApi}}/users/3